name: Build and deploy docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup 🔧
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies 📦
        run: npm ci

      - name: Create docs 🏗
        run: |
          npm run docs
          touch docs/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
