name: Test Coverage

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup 🔧
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies 📦
        run: npm ci

      - name: Create coverage report 🏗
        run: npm run test:coverage

      - name: Upload coverage to Coveralls 🚀
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
